require 'sinatra' 
require 'sinatra/contrib/all' 
require_relative './controllers/athletes_controller.rb'
require_relative './controllers/nation_controller.rb'
require_relative './controllers/event_controller.rb'